## **Chapter 7: Matrix, Array, List**

### **Exercise 1: Tạo matrix**

In [2]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)
z <- c(7, 8, 9)
v1 <- c(x, y, z)

In [7]:
matrix_1 <-matrix(v1, nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(c("r1", "r2", "r3"), c("c1", "c2", "c3")))
print("Matrix 1")
print(matrix_1)
t_matrix_1 <- t(matrix_1)
print("Ma tran chuyen vi cua matrix_1")
print(t_matrix_1)

[1] "Matrix 1"
   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9
[1] "Ma tran chuyen vi cua matrix_1"
   r1 r2 r3
c1  1  4  7
c2  2  5  8
c3  3  6  9


### **Exercise 2: Tạo và tính toán trên matrix**

In [8]:
matrix_B <- matrix(data = c(1:12), nrow = 4, dimnames = list(c("a", "b", "c", "d"), c("x", "y", "z")))
print("Matrix B:")
print(matrix_B)
tB <- t(matrix_B)

print("Transpose of Matrix B:")
print(tB)
subB<-matrix_B[2:dim(matrix_B)[1],1:3]

print("Sub of Matrix B:")
print(subB)

[1] "Matrix B:"
  x y  z
a 1 5  9
b 2 6 10
c 3 7 11
d 4 8 12
[1] "Transpose of Matrix B:"
  a  b  c  d
x 1  2  3  4
y 5  6  7  8
z 9 10 11 12
[1] "Sub of Matrix B:"
  x y  z
b 2 6 10
c 3 7 11
d 4 8 12


In [9]:
matrix_A <- matrix(data = c(1:9), nrow = 3, dimnames = list(c("a", "b", "c"), c("x", "y", "z")))
print("Matrix A:")
print(matrix_A)

A3 <- matrix_A * 3
print("3*A:")
print(A3)

A_plus_subB <- matrix_A + subB
print("A + sub B:")
print(A_plus_subB)

A_minus_subB <- matrix_A - subB
print("A - sub B:")
print(A_minus_subB)


[1] "Matrix A:"
  x y z
a 1 4 7
b 2 5 8
c 3 6 9
[1] "3*A:"
  x  y  z
a 3 12 21
b 6 15 24
c 9 18 27
[1] "A + sub B:"
  x  y  z
a 3 10 17
b 5 12 19
c 7 14 21
[1] "A - sub B:"
   x  y  z
a -1 -2 -3
b -1 -2 -3
c -1 -2 -3


### **Exercise 3: Tạo và tính toán trên matrix**

In [10]:
n = as.integer(readline(prompt = "Nhap n: "))

Nhap n: 5


In [11]:
# tao A1 co nxn phan tu ngau nhien
A1 <- matrix(runif(n*n, min = 1, max = n*n), n, n)
print("A1")
print(A1)

[1] "A1"
          [,1]      [,2]      [,3]     [,4]      [,5]
[1,]  5.820165 21.743732 20.965494 17.06167 14.961887
[2,] 20.676381 22.970453 16.490288  6.66638  2.164833
[3,] 21.657097  9.096608 11.156532 18.34019 20.262090
[4,] 12.442551  7.388384  6.442044 16.10183 13.495974
[5,]  8.999833 19.457068  8.355982 22.05690 23.418496


In [12]:
m = as.integer(readline(prompt = "Nhap m: "))

Nhap m: 10


In [13]:
# tao A2 co n*m phan tu ngau nhien
A2 <- matrix(runif(n*m, min = 1, max = n*m), n, m)
print("A2")
print(A2)

[1] "A2"
          [,1]      [,2]      [,3]     [,4]     [,5]      [,6]      [,7]
[1,] 36.971719 35.751562  1.238076 14.32177 35.92243 45.957156 34.377037
[2,] 19.260028 11.428149 22.937111 16.65874 13.30868  3.511453 49.328589
[3,] 48.340240 18.996227 39.776713 25.29754 15.93185 11.861178 11.367263
[4,]  8.454735  8.454272  8.613795 38.24142 39.31127 22.169084  4.072202
[5,] 15.431333 31.258573  6.208774 41.57468 23.93303 20.339968  9.734490
          [,8]      [,9]    [,10]
[1,]  5.072372  6.704259 39.48198
[2,] 18.178885 42.024381 15.58584
[3,] 36.408931 43.400065 20.55950
[4,] 44.569388 25.765789 38.90539
[5,] 44.564157  7.047605 24.03732


In [14]:
# tinh M biet A1 * M = A2
M <- solve(A1, A2)
print("Matrix M")
print(M)


[1] "Matrix M"
          [,1]       [,2]       [,3]       [,4]       [,5]       [,6]
[1,]  0.641484 -0.5985620  1.8295126  0.4652577 -0.5703746 -1.3206188
[2,] -1.247510  0.5680722 -0.4764762  0.6575720 -0.9068821 -0.9918855
[3,]  3.332228  0.9293341  0.7317718 -2.1230217  0.4350848  1.9765344
[4,] -4.507864 -1.3436376 -3.3185858  4.9768832  7.5153800  3.8404316
[5,]  4.505687  2.0267520  2.8224411 -2.8798453 -5.2390186 -2.1222278
           [,7]       [,8]       [,9]      [,10]
[1,]  0.4219912  1.1801370  2.2853675 -0.4879202
[2,]  1.0984259  0.5197242 -0.6021700 -1.0542926
[3,]  1.2848543 -2.7535034  0.3647430  0.8776832
[4,] -0.7339460  4.9521884  0.6563368  6.8228784
[5,] -0.4262936 -2.6641704 -0.8253474 -4.6494641


In [15]:
# hay in dong 1 cua M
print("Row 1")
print(M[1,])

[1] "Row 1"
 [1]  0.6414840 -0.5985620  1.8295126  0.4652577 -0.5703746 -1.3206188
 [7]  0.4219912  1.1801370  2.2853675 -0.4879202


In [16]:
# hay in cot 1 cua M
print("Column 1")
print(M[,1])


[1] "Column 1"
[1]  0.641484 -1.247510  3.332228 -4.507864  4.505687


In [17]:
# hay in gia tri dong 3 cot 2 cua M
if (n>=3 && m>=2){
    print("M[3][2]")
    print(M[3,2])
}


[1] "M[3][2]"
[1] 0.9293341


### **Exercise 4: Tạo và tính toán trên array**

In [18]:
matrix_1 <- matrix(c(1:9),nrow = 3, byrow = TRUE)
matrix_2 <- matrix(c(10:18),nrow = 3, byrow = TRUE)
A3 <- array(c(matrix_1, matrix_2), dim = c(3, 3, 2), dimnames = list(c("r1", "r2", "r3"), 
                                                    c("c1", "c2", "c3"), 
                                                    c("matrix1", "matrix2")))
print("Array A3:")
print(A3)


[1] "Array A3:"
, , matrix1

   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9

, , matrix2

   c1 c2 c3
r1 10 11 12
r2 13 14 15
r3 16 17 18



In [19]:
#tong theo dong cua tat ca matrix
print("Tong theo dong cua tat ca matrix")
print(apply(A3, c(1),sum))

#tong theo cot cua tat ca matrix
print("Tong theo cot cua tat ca matrix")
print(apply(A3, c(2),sum))

# tong tat ca matrix
print("Tong theo matrix cua array")
print(apply(A3, c(3),sum))
print("Tong dong 1, matrix1")
print(sum(A3[1,,1]))
print("Tich cot 2, matrix2")
print(prod(A3[, 2,2]))

[1] "Tong theo dong cua tat ca matrix"
r1 r2 r3 
39 57 75 
[1] "Tong theo cot cua tat ca matrix"
c1 c2 c3 
51 57 63 
[1] "Tong theo matrix cua array"
matrix1 matrix2 
     45     126 
[1] "Tong dong 1, matrix1"
[1] 6
[1] "Tich cot 2, matrix2"
[1] 2618


### **Exercise 5: Tạo và tính toán trên array**

In [20]:
v <- c()
i <-1
while(i<=50){
    x = floor(runif(1, min = 5, max = 50))
    if (x%%2==0){
        v[i] <-x
        i <- i + 1
    }
}

print(v)


 [1] 30 26 44 30 20 46 46 12 34 16 28 14 16  8 10 38 24 42 22 22 46 40 48 30 10
[26] 20 12 26 28 18 34 46 34  8 26 42 22 36 32  8 20  6  6 38 46 34 42 34  8 16


In [21]:
A4 <- array(v, dim=c(5, 5, 2))
print("Array A4:")
print(A4)

[1] "Array A4:"
, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   30   46   28   38   46
[2,]   26   46   14   24   40
[3,]   44   12   16   42   48
[4,]   30   34    8   22   30
[5,]   20   16   10   22   10

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   20   34   42   20   34
[2,]   12   46   22    6   42
[3,]   26   34   36    6   34
[4,]   28    8   32   38    8
[5,]   18   26    8   46   16



In [22]:
rows <- nrow(A4)
print(rows)
cols <- ncol(A4)
print(cols)
dims <- dim(A4)[3]
print(dims)

[1] 5
[1] 5
[1] 2


In [23]:
i <- 1
j <- 1
k <- 1
tong <-0
while(i<=dims){
    #print(paste("Matrix ", i))
    j <-1
    while(j<=rows){
        #print(paste("row ", j))
        k <-1
        while(k<=cols){
            #print(paste("col ", k))
            if(A4[j,k,i]%% 2 == 0 & A4[j,k,i]%% 3 == 0 & A4[j,k,i]%% 6 == 0){
                print(paste("A4[", j,",", k,",", i,"] =", A4[j,k,i]))
                tong <- tong + A4[j,k,i]
            }
            k <- k+1
        }
        j <- j+1
    }
    i <- i+1
}

print(paste("Tong =", tong))


[1] "A4[ 1 , 1 , 1 ] = 30"
[1] "A4[ 2 , 4 , 1 ] = 24"
[1] "A4[ 3 , 2 , 1 ] = 12"
[1] "A4[ 3 , 4 , 1 ] = 42"
[1] "A4[ 3 , 5 , 1 ] = 48"
[1] "A4[ 4 , 1 , 1 ] = 30"
[1] "A4[ 4 , 5 , 1 ] = 30"
[1] "A4[ 1 , 3 , 2 ] = 42"
[1] "A4[ 2 , 1 , 2 ] = 12"
[1] "A4[ 2 , 4 , 2 ] = 6"
[1] "A4[ 2 , 5 , 2 ] = 42"
[1] "A4[ 3 , 3 , 2 ] = 36"
[1] "A4[ 3 , 4 , 2 ] = 6"
[1] "A4[ 5 , 1 , 2 ] = 18"
[1] "Tong = 378"


### **Exercise 6: Tạo và tính toán trên list**

In [24]:
p <- c(2,7,8)
q <- c("A", "B", "C")
x <- list(p, q)
print("List x:")
print(x)

[1] "List x:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "B" "C"



In [25]:
# in gia tri cua x tai vi tri thu 2
print(paste("list[2]: ",toString(x[2])))

# in gia tri phan tu thu 2 cua vector thu 2 trong list
print(paste("vector[2] of list[2]:", x[[2]][2]))

# thay the phan tu thu 2 cua vector thu 2 trong list thanh "K"
x[[2]][2]<- "K"
print("List after changing")
print(x)

[1] "list[2]:  c(\"A\", \"B\", \"C\")"
[1] "vector[2] of list[2]: B"
[1] "List after changing"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"



In [26]:
# them t<-c(1, 3, 4) vao list
#cach 1
t<- c(1, 3, 4)
x <- c(x, list(t))
print("List after insert:")
print(x)

#cach 2
x[length(x)+1]<-list(t)
print(x)

[1] "List after insert:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"

[[3]]
[1] 1 3 4

[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"

[[3]]
[1] 1 3 4

[[4]]
[1] 1 3 4



In [27]:
a <- list ("x"=5, "y"=10, "z"=15)
print("List a:")
print(a)

#tinh tong cua list
print(paste("Sum of list:", sum(unlist(a))))


[1] "List a:"
$x
[1] 5

$y
[1] 10

$z
[1] 15

[1] "Sum of list: 30"


In [28]:
Newlist <- list(a=1:10, b="Good morning", c="Hi")
print("Newlist:")
print(Newlist)
#cong them 1 vao cac phan tu cua element a trong list
Newlist$a <-Newlist$a+1
print(Newlist)

[1] "Newlist:"
$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
[1] "Good morning"

$c
[1] "Hi"

$a
 [1]  2  3  4  5  6  7  8  9 10 11

$b
[1] "Good morning"

$c
[1] "Hi"



### **Exercise 7: Tạo và tính toán trên list**

In [29]:
# cho 3 vector day, month, year => tao 1 list chua 3 element nay
year <- c(2008:2018)
month <- c(1:12)
day <- c(1:31)
# list
year_month_day.list <- list("year" = year, "month" = month, "day" = day)
print("List year_month_day:")
print(year_month_day.list)


[1] "List year_month_day:"
$year
 [1] 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [30]:
# cap nhat year thanh c(2010:2020)
year_month_day.list$year <- c(2010:2020)
print("List year_month_day after changing:")
print(year_month_day.list)

[1] "List year_month_day after changing:"
$year
 [1] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [31]:
# bo nam dau tien trong year cua list
#x <- length(year_month_day.list$year)
year_month_day.list$year <- year_month_day.list$year[-1]
print("After drop the first year in year:")
print(year_month_day.list)


[1] "After drop the first year in year:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [32]:
x <- c(1,3,4,7,11,18,29)
cal.list <- list("x*2"= x*2,"x/2"=x/2, "sqrt(x)"=sqrt(x))
print("List calculator:")
print(cal.list)
#tra ve cac phan tu 3-5 $sqrt(x)
print("3 phan tu giua")
print(cal.list$`sqrt(x)`[3:5])

[1] "List calculator:"
$`x*2`
[1]  2  6  8 14 22 36 58

$`x/2`
[1]  0.5  1.5  2.0  3.5  5.5  9.0 14.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 5.385165

[1] "3 phan tu giua"
[1] 2.000000 2.645751 3.316625


In [33]:
#tao 1 list moi co 2 list tren
year_month_day_cal.list <- c(year_month_day.list, cal.list)
print("year_month_day_cal.list: ")
print(year_month_day_cal.list)


[1] "year_month_day_cal.list: "
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31

$`x*2`
[1]  2  6  8 14 22 36 58

$`x/2`
[1]  0.5  1.5  2.0  3.5  5.5  9.0 14.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 5.385165



In [34]:
# tao mot list con chua year, x*2 va day tu list moi tao ra tren
year_x2_day <- year_month_day_cal.list[c("year", "x*2", "day")]
print("list year_x2_day:")
print(year_x2_day)

[1] "list year_x2_day:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$`x*2`
[1]  2  6  8 14 22 36 58

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [35]:
# chieu dai cua x*2
print(paste("length of x*2:", length(year_x2_day$`x*2`)))
print(paste("last value of year:", 
 year_x2_day$year[length(year_x2_day$year)]))

[1] "length of x*2: 7"
[1] "last value of year: 2020"


### **Exercise 8: Tạo và tính toán trên list**

In [37]:
# cho list
y <- list(c("a", "b", "c"), c(1,2,3),10)
#dat ten
names(y) <- c("one", "two", "three")
print("List y:")
print(y)


[1] "List y:"
$one
[1] "a" "b" "c"

$two
[1] 1 2 3

$three
[1] 10



In [38]:
# chieu dai
print(paste("Length of one, two, three are:", 
            length(y$one), ",", 
            length(y$two), ",", 
            length(y$three))
)


[1] "Length of one, two, three are: 3 , 3 , 1"


In [39]:
z <- list(c("a", "b", "c"), c(1,3,5,7),TRUE)
print("list z:")
print(z)

[1] "list z:"
[[1]]
[1] "a" "b" "c"

[[2]]
[1] 1 3 5 7

[[3]]
[1] TRUE



In [40]:
# in y not in z 
t <- setdiff(y, z)
print("in y not in z:")
print(t)
#in z not in y
f <- setdiff(z, y)
print("in z not in y")
print(f)

[1] "in y not in z:"
[[1]]
[1] 1 2 3

[[2]]
[1] 10

[1] "in z not in y"
[[1]]
[1] 1 3 5 7

[[2]]
[1] TRUE

