# Bài tập tuần 2
## Bài tập số 1:

In [6]:
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

# Create survey_vector as a factor: survey_factor
survey_factor = as.factor(survey_vector)

# Print survey_factor
print(survey_factor)

# Print levels of survey_factor
print(paste("Levels in factor:", toString(levels(survey_factor))))

# Print nlevels of survey_factor
print(paste("Levels in factor:", toString(nlevels(survey_factor))))

# How many elements of each factor?
print('num of elements of each factor')
print(table(survey_factor))

[1] R R L L R R C C
Levels: C L R
[1] "\nLevels in factor: C, L, R"
[1] "Levels in factor: 3"
[1] "num of elements of each factor"
survey_factor
C L R 
2 2 4 


## Bài tập số 2:


In [32]:
# Create my_vector: 1 up to 10
my_vector = c(1:10)
print('my_vector:')
print(my_vector)
print('----------------------------------------')
# Create my_matrix (3x3): 1 up to 9
my_matrix = matrix(c(1:9), nrow=3, byrow=TRUE)
print('my_matrix:')
print(my_matrix)
print('----------------------------------------')

# Create my_factor from sizes
sizes <-c("M","S","L","L","M")
my_factor = factor(sizes)
print('my_factor:')
print(my_factor)
print('----------------------------------------')

# Construct my_list with the three data structures above
my_list = list(my_vector, my_matrix, my_factor)
print('my_list')
print(my_list)
print('----------------------------------------')

# Construct my_super_list with the four data structures above
my_super_list = list(my_vector, my_matrix, my_factor, my_list)
print('my_super_list')
print(my_super_list)
print('----------------------------------------')

# Display structure of my_super_list (Use str())
print(str(my_super_list))

# Print my_matrix, sum of my_matrix, sum of even elements in my_matrix
print(my_matrix)
print(paste('sum of matrix', sum(my_matrix)))

sum_even = 0
for (i in 1:nrow(my_matrix))
{
    for (j in 1:ncol(my_matrix))
    {
        if (my_matrix[i, j] %% 2 == 0)
            sum_even = sum_even + my_matrix[i, j]
    }
}

print(paste('sum of even elements in my_matrix: ', sum_even))


[1] "my_vector:"
 [1]  1  2  3  4  5  6  7  8  9 10
[1] "----------------------------------------"
[1] "my_matrix:"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[1] "----------------------------------------"
[1] "my_factor:"
[1] M S L L M
Levels: L M S
[1] "----------------------------------------"
[1] "my_list"
[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
[1] M S L L M
Levels: L M S

[1] "----------------------------------------"
[1] "my_super_list"
[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
[1] M S L L M
Levels: L M S

[[4]]
[[4]][[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[4]][[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[4]][[3]]
[1] M S L L M
Levels: L M S


[1] "----------------------------------------"
List of 4
 $ : int [1:1

## Bài tập số 3:


In [47]:
create_primes <- function(n){
    primesR <- function(p, i = 1){
        f <- p %% p[i] == 0 & p != p[i]
        if (any(f)){
            p <- primesR(p[!f], i+1)
        }
        p
    }
    primesR(2:n)
}

In [112]:
primes_list = create_primes(100) # generate vector primes from 2 to n with n < 100

In [120]:
# Create my_matrix (4x4): each element is a randomly generated prime number.
my_matrix = matrix(sample(primes_list, 16), nrow = 4)
print(my_matrix)

# Sum the elements on the main diagonal of the matrix
print(paste('Sum the elements on the main diagonal of the matrix: ', sum(diag(my_matrix))))


# (Note: Build function to create_matrix, function to test_Prime number, and function to Sum... >> Call fucntion)
# function to create_matrix
create_prime_matrix <- function(max_number, n_rows, n_cols){
    primes_vector = create_primes(max_number)
    return (matrix(sample(primes_vector, n_rows*n_cols), nrow = n_rows, ncol=n_cols))
}

# function to test_Prime number
is_prime <- function(num) {
    if (num == 2) {
        TRUE
    } else if (any(num %% 2:(num-1) == 0)) {
        FALSE
    } else { 
        TRUE
    }
}

# function Sum the elements on the main diagonal of the matrix
sum_diag_matrix <- function(matrixx)
{
    return (sum(diag(matrixx)))
}


     [,1] [,2] [,3] [,4]
[1,]   83   73   43   61
[2,]   29   19    2    5
[3,]   17   53   11   41
[4,]   67    3   37   23
[1] "Sum the elements on the main diagonal of the matrix:  136"


In [121]:
matrix_2 = create_prime_matrix(10000, 8, 8)
matrix_2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 6203 3371 9851 4937 8353 9241 1531 2999
[2,] 9371 7919 4993 3041 5821 3067 8461 2647
[3,] 3881 2389 2657 5903 3917 6037 4637 2129
[4,] 9209 5351 1481 3779  431 8093 2789 1789
[5,] 6277 2729 7523 1579 1087 1801 5281 2447
[6,]  929 3373 8219 3119  547 3229 4253  193
[7,] 2797 6481 5783   53 5869  673 3049 8111
[8,] 3319 8053  151 4327 3251 3907 5477 4231

In [99]:
is_prime(3)
is_prime(11)
is_prime(10)

[1] TRUE

[1] TRUE

[1] FALSE

In [122]:
sum_diag_matrix(matrix_2)

[1] 32154

## Bài tập số 4:

In [123]:
matrix_1 = create_prime_matrix(100, 4, 4)
matrix_1

matrix_2 = create_prime_matrix(100, 4, 4)
matrix_2

[,1] [,2] [,3] [,4]
[1,]  3   13   83    7  
[2,] 29   73   31   41  
[3,] 11   97   79   53  
[4,] 19   37    2   71

[,1] [,2] [,3] [,4]
[1,] 37   97   43   83  
[2,] 19    2   79   41  
[3,] 23   47   89   31  
[4,] 29   13    3   17

In [138]:
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Bai tap so 3)
my_array = array(c(matrix_1, matrix_2), dim = c(4, 4, 2))
print(my_array)

# Use apply to calculate the min of the rows across all the matrices.
print('minimum value of each row on all matrices:')
print(apply(my_array, 1, min))

# Use apply to calculate the max of the columns across all the matrices.
print('maximum value of each column on all matrices')
print(apply(my_array, 1, max))

# Use apply to calculate the sum of each matrix in my_array
print('sum of each matrix')
print(apply(my_array, 3,sum))

, , 1

     [,1] [,2] [,3] [,4]
[1,]    3   13   83    7
[2,]   29   73   31   41
[3,]   11   97   79   53
[4,]   19   37    2   71

, , 2

     [,1] [,2] [,3] [,4]
[1,]   37   97   43   83
[2,]   19    2   79   41
[3,]   23   47   89   31
[4,]   29   13    3   17

[1] "minimum value of each row on all matrices:"
[1]  3  2 11  2
[1] "maximum value of each column on all matrices"
[1] 97 79 97 71
[1] "sum of each matrix"
[1] 649 653


## Bài tập số 5

In [180]:
# Create title, actors, reviews
title = "The Shining"
actors_vector <- c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson")
reviews_factor <- factor(c("Good", "OK", "Good", "Perfect", "Bad", "Perfect", "Good"), 
                  ordered = TRUE, levels = c("Bad", "OK", "Good", "Perfect"))

# Create the list 'shining_list' from 3 vectors above
shining_list = list(title, actors_vector, reviews_factor)
print(shining_list)

# Select the last actor from list: last_actor
last_actor = unlist(shining_list[2])[length(unlist(shining_list[2]))]
print(paste('last actor from list: ', last_actor))

# Select the second review from list: second_review
second_review = unlist(shining_list[3])[2]
print(paste('second review from list: ', second_review))

# Add the element 'release_year' = 1980 to shining_list
release_year = 1980
shining_list[length(shining_list)+1] = release_year

# Add the element 'director' = "Stanley Kubrick" to shining_list
director = 'Stanley Kubrick'
shining_list[length(shining_list)+1] = director

# Print list shining_list
print(shining_list)

# Print the structure of shining_list
print(str(shining_list))

[[1]]
[1] "The Shining"

[[2]]
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

[[3]]
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

[1] "last actor from list:  Barry Nelson"
[1] "second review from list:  OK"
[[1]]
[1] "The Shining"

[[2]]
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

[[3]]
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

[[4]]
[1] 1980

[[5]]
[1] "Stanley Kubrick"

List of 5
 $ : chr "The Shining"
 $ : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ : num 1980
 $ : chr "Stanley Kubrick"
NULL


## Bài tập số 6: Hãy thực hiện những yêu cầu sau với R-core dataframe và/ hoặc Tidyverse
1. Cho dữ liệu mtcars cho sẵn trong R datasets. Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
2. Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
3. Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
4. Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct()
5. In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
6. Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
7. Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
8. Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
9. Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất
10. Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?

#### Note: dùng df = cbind(names = rownames(df), df) hoặc rownames_to_column(df, var = "names"): chuyển cột index thành cột "names"

In [224]:
install.packages('quantmod')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘xts’, ‘zoo’, ‘TTR’




In [225]:
library(tidyverse)
library(quantmod)

Loading required package: xts

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric



Attaching package: ‘xts’


The following objects are masked from ‘package:dplyr’:

    first, last


Loading required package: TTR

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 



In [187]:
# Cho dữ liệu mtcars cho sẵn trong R datasets. Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
data(mtcars)

head(mtcars)
summary(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

In [189]:
# Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
sub_data = select(mtcars, mpg, hp, wt, gear)
head(sub_data)

mpg  hp  wt    gear
Mazda RX4         21.0 110 2.620 4   
Mazda RX4 Wag     21.0 110 2.875 4   
Datsun 710        22.8  93 2.320 4   
Hornet 4 Drive    21.4 110 3.215 3   
Hornet Sportabout 18.7 175 3.440 3   
Valiant           18.1 105 3.460 3

In [191]:
# Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
sub_data$km_per_litre = sub_data$mpg * 0.425
head(sub_data)

mpg  hp  wt    gear km_per_litre
Mazda RX4         21.0 110 2.620 4    8.9250      
Mazda RX4 Wag     21.0 110 2.875 4    8.9250      
Datsun 710        22.8  93 2.320 4    9.6900      
Hornet 4 Drive    21.4 110 3.215 3    9.0950      
Hornet Sportabout 18.7 175 3.440 3    7.9475      
Valiant           18.1 105 3.460 3    7.6925

In [242]:
# Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct())
print(dim(mtcars))
sub_data_unique = distinct(mtcars)
head(sub_data_unique)
print(dim(sub_data_unique))

[1] 32 11


mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

[1] 32 11


In [243]:
# In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
arrange(sub_data_unique, hp, desc(mpg))

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8

In [244]:
sub_data_unique = cbind(names = rownames(sub_data_unique), sub_data_unique)
head(sub_data_unique)

names             mpg  cyl disp hp  drat wt    qsec  vs am
Mazda RX4         Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1 
Mazda RX4 Wag     Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1 
Datsun 710        Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1 
Hornet 4 Drive    Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0 
Hornet Sportabout Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0 
Valiant           Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0 
                  gear carb
Mazda RX4         4    4   
Mazda RX4 Wag     4    4   
Datsun 710        4    1   
Hornet 4 Drive    3    1   
Hornet Sportabout 3    2   
Valiant           3    1

In [245]:
# Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
filter(sub_data_unique, grepl('Mazda', sub_data_unique$names, fixed=TRUE))

names         mpg cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     Mazda RX4     21  6   160  110 3.9  2.620 16.46 0  1  4    4   
Mazda RX4 Wag Mazda RX4 Wag 21  6   160  110 3.9  2.875 17.02 0  1  4    4

In [247]:
# Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
print(paste('maximum mpg: ', max(sub_data_unique$mpg)))
filter(sub_data_unique, mpg == max(mpg))

[1] "maximum mpg:  33.9"


names          mpg  cyl disp hp drat wt    qsec vs am gear carb
Toyota Corolla Toyota Corolla 33.9 4   71.1 65 4.22 1.835 19.9 1  1  4    1

In [248]:
# Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
filter(sub_data_unique, mpg >= 25, cyl==4, gear==4)

names          mpg  cyl disp hp drat wt    qsec  vs am gear carb
Fiat 128       Fiat 128       32.4 4   78.7 66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    Honda Civic    30.4 4   75.7 52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla Toyota Corolla 33.9 4   71.1 65 4.22 1.835 19.90 1  1  4    1   
Fiat X1-9      Fiat X1-9      27.3 4   79.0 66 4.08 1.935 18.90 1  1  4    1

In [255]:
# Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất
summary(sub_data_unique$cyl)

df_group = group_by(sub_data_unique, cyl)
summarize(  df_group, 
            count=n(),
            max.hp = max(sub_data_unique$hp, na.rm=T),
            min.mpg = min(sub_data_unique$mpg, na.rm=T)
)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.000   4.000   6.000   6.188   8.000   8.000 

cyl count max.hp min.mpg
1 4   11    335    10.4   
2 6    7    335    10.4   
3 8   14    335    10.4

In [259]:
# Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?
filter(sub_data, km_per_litre == max(km_per_litre))
filter(sub_data, km_per_litre == min(km_per_litre))

mpg  hp wt    gear km_per_litre
Toyota Corolla 33.9 65 1.835 4    14.4075

mpg  hp  wt    gear km_per_litre
Cadillac Fleetwood  10.4 205 5.250 3    4.42        
Lincoln Continental 10.4 215 5.424 3    4.42